In [1]:
import importlib
import os
import time
!pip install hydesign
import yaml
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from hydesign.assembly.hpp_assembly import hpp_model
from hydesign.examples import examples_filepath

Collecting hydesign
  Using cached hydesign-1.6.1-py3-none-any.whl.metadata (5.0 kB)
Collecting numpy<2.4.3,>=2 (from hydesign)
  Using cached numpy-2.4.2-cp314-cp314-win_amd64.whl.metadata (6.6 kB)
Collecting pandas (from hydesign)
  Using cached pandas-3.0.3-cp314-cp314-win_amd64.whl.metadata (19 kB)
Collecting scipy (from hydesign)
  Using cached scipy-1.18.0-cp314-cp314-win_amd64.whl.metadata (61 kB)
Collecting h5netcdf (from hydesign)
  Using cached h5netcdf-1.8.1-py3-none-any.whl.metadata (15 kB)
Collecting netcdf4 (from hydesign)
  Using cached netcdf4-1.7.4-cp311-abi3-win_amd64.whl.metadata (2.1 kB)
Collecting xarray (from hydesign)
  Using cached xarray-2026.4.0-py3-none-any.whl.metadata (12 kB)
Collecting openmdao (from hydesign)
  Using cached openmdao-3.44.0-py3-none-any.whl.metadata (11 kB)
Collecting smt==2.9.2 (from hydesign)
  Using cached smt-2.9.2.tar.gz (433 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting jenn==1.0.8 (from hydesign)
  Using cached jenn-1.0.8-py3-none-any.whl.metadata (7.8 kB)
Collecting cplex (from hydesign)
  Using cached cplex-22.2.0.0-cp314-cp314-win_amd64.whl.metadata (56 kB)
Collecting docplex (from hydesign)
  Using cached docplex-2.32.264-py3-none-any.whl
Collecting numpy-financial (from hydesign)
  Using cached numpy_financial-1.0.0-py3-none-any.whl.metadata (2.2 kB)
Collecting pvlib (from hydesign)
  Using cached pvlib-0.15.2-py3-none-any.whl.metadata (2.9 kB)
Collecting statsmodels (from hydesign)
  Using cached statsmodels-0.14.6-cp314-cp314-win_amd64.whl.metadata (9.8 kB)
Collecting rainflow (from hydesign)
  Using cached rainflow-3.2.0-py3-none-any.whl.metadata (3.6 kB)
Collecting pyyaml (from hydesign)
  Using cached pyyaml-6.0.3-cp314-cp314-win_amd64.whl.metadata (2.4 kB)
Collecting matplotlib (from hydesign)
  Using cached matplotlib-3.11.0-cp314-cp314-win_amd64.whl.metadata (80 kB)
Collecting ortools (from hydesign)
  Using cached ortools-9.15.6755-cp314-cp314-win_amd64.whl.metadata (3.4 kB)
INFO: pip is looking at multiple versions of hydesign to determine which version is compatible with other requirements. This could take a while.
Collecting hydesign
  Using cached hydesign-1.6.0-py3-none-any.whl.metadata (4.9 kB)
Collecting numpy>=2 (from hydesign)
  Using cached numpy-2.5.0-cp314-cp314-win_amd64.whl.metadata (6.6 kB)
Collecting hydesign
  Using cached hydesign-1.5.3-py3-none-any.whl.metadata (4.4 kB)
Collecting dask (from hydesign)
  Using cached dask-2026.6.0-py3-none-any.whl.metadata (3.8 kB)
Collecting scikit-learn (from hydesign)
  Using cached scikit_learn-1.9.0-cp314-cp314-win_amd64.whl.metadata (11 kB)
Collecting zarr (from hydesign)
  Using cached zarr-3.2.1-py3-none-any.whl.metadata (8.7 kB)
Collecting hydesign
  Using cached hydesign-1.5.2-py3-none-any.whl.metadata (4.4 kB)
  Using cached hydesign-1.4.1-py3-none-any.whl.metadata (4.4 kB)
Collecting smt (from hydesign)
  Using cached smt-2.14.1-cp314-cp314-win_amd64.whl.metadata (7.6 kB)
Collecting hydesign
  Using cached hydesign-1.4.0-py3-none-any.whl.metadata (4.4 kB)
  Using cached hydesign-1.3.4-py3-none-any.whl.metadata (4.3 kB)
  Using cached hydesign-1.3.2-py3-none-any.whl.metadata (4.2 kB)
Collecting finitediff (from hydesign)
  Using cached finitediff-0.6.6.tar.gz (200 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Installing backend dependencies: started
  Installing backend dependencies: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting smt==2.0 (from hydesign)
  Using cached smt-2.0.tar.gz (272 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting pyDOE2 (from smt==2.0->hydesign)
  Using cached pydoe2-1.3.0-py3-none-any.whl
Collecting click>=8.1 (from dask->hydesign)
  Using cached click-8.4.1-py3-none-any.whl.metadata (2.6 kB)
Collecting cloudpickle>=3.0.0 (from dask->hydesign)
  Using cached cloudpickle-3.1.2-py3-none-any.whl.metadata (7.1 kB)
Collecting fsspec>=2021.09.0 (from dask->hydesign)
  Using cached fsspec-2026.6.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: packaging>=20.0 in C:\Users\ntagkrasd\emerge_benchmarking\venv\Lib\site-packages (from dask->hydesign) (26.2)
Collecting partd>=1.4.0 (from dask->hydesign)
  Using cached partd-1.4.2-py3-none-any.whl.metadata (4.6 kB)
Collecting toolz>=0.12.0 (from dask->hydesign)
  Using cached toolz-1.1.0-py3-none-any.whl.metadata (5.1 kB)
Requirement already satisfied: colorama in C:\Users\ntagkrasd\emerge_benchmarking\venv\Lib\site-packages (from click>=8.1->dask->hydesign) (0.4.6)
Collecting locket (from partd>=1.4.0->dask->hydesign)
  Using cached locket-1.0.0-py2.py3-none-any.whl.metadata (2.8 kB)
Requirement already satisfied: six in C:\Users\ntagkrasd\emerge_benchmarking\venv\Lib\site-packages (from docplex->hydesign) (1.17.0)
Collecting contourpy>=1.0.1 (from matplotlib->hydesign)
  Using cached contourpy-1.3.3-cp314-cp314-win_amd64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib->hydesign)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib->hydesign)
  Using cached fonttools-4.63.0-cp314-cp314-win_amd64.whl.metadata (121 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib->hydesign)
  Using cached kiwisolver-1.5.0-cp314-cp314-win_amd64.whl.metadata (5.2 kB)
Collecting pillow>=9 (from matplotlib->hydesign)
  Using cached pillow-12.2.0-cp314-cp314-win_amd64.whl.metadata (9.0 kB)
Collecting pyparsing>=3 (from matplotlib->hydesign)
  Using cached pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: python-dateutil>=2.7 in C:\Users\ntagkrasd\emerge_benchmarking\venv\Lib\site-packages (from matplotlib->hydesign) (2.9.0.post0)
Collecting cftime (from netcdf4->hydesign)
  Using cached cftime-1.6.5-cp314-cp314-win_amd64.whl.metadata (8.8 kB)
Collecting certifi (from netcdf4->hydesign)
  Using cached certifi-2026.6.17-py3-none-any.whl.metadata (2.5 kB)
Collecting networkx>=3.3 (from openmdao->hydesign)
  Using cached networkx-3.6.1-py3-none-any.whl.metadata (6.8 kB)
Collecting requests (from openmdao->hydesign)
  Using cached requests-2.34.2-py3-none-any.whl.metadata (4.8 kB)
Collecting tzdata (from pandas->hydesign)
  Using cached tzdata-2026.2-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting pytz (from pvlib->hydesign)
  Using cached pytz-2026.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting h5py (from pvlib->hydesign)
  Using cached h5py-3.16.0-cp314-cp314-win_amd64.whl.metadata (3.1 kB)
Collecting charset_normalizer<4,>=2 (from requests->openmdao->hydesign)
  Using cached charset_normalizer-3.4.7-cp314-cp314-win_amd64.whl.metadata (41 kB)
Collecting idna<4,>=2.5 (from requests->openmdao->hydesign)
  Using cached idna-3.18-py3-none-any.whl.metadata (6.1 kB)
Collecting urllib3<3,>=1.26 (from requests->openmdao->hydesign)
  Using cached urllib3-2.7.0-py3-none-any.whl.metadata (6.9 kB)
Collecting joblib>=1.4.0 (from scikit-learn->hydesign)
  Using cached joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting narwhals>=2.0.1 (from scikit-learn->hydesign)
  Using cached narwhals-2.22.1-py3-none-any.whl.metadata (15 kB)
Collecting threadpoolctl>=3.5.0 (from scikit-learn->hydesign)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Collecting patsy>=0.5.6 (from statsmodels->hydesign)
  Using cached patsy-1.0.2-py2.py3-none-any.whl.metadata (3.6 kB)
Collecting donfig>=0.8 (from zarr->hydesign)
  Using cached donfig-0.8.1.post1-py3-none-any.whl.metadata (5.0 kB)
Collecting google-crc32c>=1.5 (from zarr->hydesign)
  Using cached google_crc32c-1.8.0-cp314-cp314-win_amd64.whl.metadata (1.8 kB)
Collecting numcodecs>=0.14 (from zarr->hydesign)
  Using cached numcodecs-0.16.5-cp314-cp314-win_amd64.whl.metadata (3.5 kB)
Requirement already satisfied: typing-extensions>=4.13 in C:\Users\ntagkrasd\emerge_benchmarking\venv\Lib\site-packages (from zarr->hydesign) (4.15.0)
Using cached hydesign-1.3.2-py3-none-any.whl (38.7 MB)
Using cached cplex-22.2.0.0-cp314-cp314-win_amd64.whl (32.7 MB)
Using cached dask-2026.6.0-py3-none-any.whl (1.5 MB)
Using cached click-8.4.1-py3-none-any.whl (116 kB)
Using cached cloudpickle-3.1.2-py3-none-any.whl (22 kB)
Using cached fsspec-2026.6.0-py3-none-any.whl (203 kB)
Using cached partd-1.4.2-py3-none-any.whl (18 kB)
Using cached pyyaml-6.0.3-cp314-cp314-win_amd64.whl (156 kB)
Using cached toolz-1.1.0-py3-none-any.whl (58 kB)
Using cached h5netcdf-1.8.1-py3-none-any.whl (62 kB)
Using cached locket-1.0.0-py2.py3-none-any.whl (4.4 kB)
Using cached matplotlib-3.11.0-cp314-cp314-win_amd64.whl (9.5 MB)
Using cached contourpy-1.3.3-cp314-cp314-win_amd64.whl (232 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Using cached fonttools-4.63.0-cp314-cp314-win_amd64.whl (2.3 MB)
Using cached kiwisolver-1.5.0-cp314-cp314-win_amd64.whl (75 kB)
Using cached numpy-2.5.0-cp314-cp314-win_amd64.whl (12.6 MB)
Using cached pillow-12.2.0-cp314-cp314-win_amd64.whl (7.2 MB)
Using cached pyparsing-3.3.2-py3-none-any.whl (122 kB)
Using cached netcdf4-1.7.4-cp311-abi3-win_amd64.whl (21.3 MB)
Using cached certifi-2026.6.17-py3-none-any.whl (133 kB)
Using cached cftime-1.6.5-cp314-cp314-win_amd64.whl (463 kB)
Using cached numpy_financial-1.0.0-py3-none-any.whl (14 kB)
Using cached openmdao-3.44.0-py3-none-any.whl (13.8 MB)
Using cached networkx-3.6.1-py3-none-any.whl (2.1 MB)
Using cached scipy-1.18.0-cp314-cp314-win_amd64.whl (37.3 MB)
Using cached pandas-3.0.3-cp314-cp314-win_amd64.whl (9.9 MB)
Using cached pvlib-0.15.2-py3-none-any.whl (19.4 MB)
Using cached h5py-3.16.0-cp314-cp314-win_amd64.whl (3.2 MB)
Using cached pytz-2026.2-py2.py3-none-any.whl (510 kB)
Using cached rainflow-3.2.0-py3-none-any.whl (4.9 kB)
Using cached requests-2.34.2-py3-none-any.whl (73 kB)
Using cached charset_normalizer-3.4.7-cp314-cp314-win_amd64.whl (159 kB)
Using cached idna-3.18-py3-none-any.whl (65 kB)
Using cached urllib3-2.7.0-py3-none-any.whl (131 kB)
Using cached scikit_learn-1.9.0-cp314-cp314-win_amd64.whl (8.3 MB)
Using cached joblib-1.5.3-py3-none-any.whl (309 kB)
Using cached narwhals-2.22.1-py3-none-any.whl (454 kB)
Using cached threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Using cached statsmodels-0.14.6-cp314-cp314-win_amd64.whl (9.6 MB)
Using cached patsy-1.0.2-py2.py3-none-any.whl (233 kB)
Using cached tzdata-2026.2-py2.py3-none-any.whl (349 kB)
Using cached xarray-2026.4.0-py3-none-any.whl (1.4 MB)
Using cached zarr-3.2.1-py3-none-any.whl (319 kB)
Using cached donfig-0.8.1.post1-py3-none-any.whl (21 kB)
Using cached google_crc32c-1.8.0-cp314-cp314-win_amd64.whl (34 kB)
Using cached numcodecs-0.16.5-cp314-cp314-win_amd64.whl (819 kB)
Building wheels for collected packages: smt, finitediff
  Building wheel for smt (pyproject.toml): started
  Building wheel for smt (pyproject.toml): finished with status 'done'
  Created wheel for smt: filename=smt-2.0-cp314-cp314-win_amd64.whl size=265203 sha256=d5fcf315c99baaf28dfe273d43feae2f7566ad46fd88243b9721b1e4f142f752
  Stored in directory: c:\users\ntagkrasd\appdata\local\pip\cache\wheels\dd\74\78\4f9fed3bee0b039da6b657c316eb2acea89ebdf28af7cc0d8a
  Building wheel for finitediff (pyproject.toml): started
  Building wheel for finitediff (pyproject.toml): finished with status 'done'
  Created wheel for finitediff: filename=finitediff-0.6.6-cp314-cp314-win_amd64.whl size=174826 sha256=ef970d554d85378228dc9b5a70cf836f597e71abdd9560e3b3a432c809f06e6e
  Stored in directory: c:\users\ntagkrasd\appdata\local\pip\cache\wheels\b9\27\2d\edf7e9073a01ff355a2e7114f4404fe4bfccdfc53c2e130e08
Successfully built smt finitediff
Installing collected packages: pytz, urllib3, tzdata, toolz, threadpoolctl, rainflow, pyyaml, pyparsing, pillow, numpy, networkx, narwhals, locket, kiwisolver, joblib, idna, google-crc32c, fsspec, fonttools, docplex, cycler, cplex, cloudpickle, click, charset_normalizer, certifi, scipy, requests, patsy, partd, pandas, numpy-financial, numcodecs, h5py, h5netcdf, finitediff, donfig, contourpy, cftime, zarr, xarray, statsmodels, scikit-learn, pyDOE2, pvlib, openmdao, netcdf4, matplotlib, dask, smt, hydesign

   ----------------------------------------  0/51 [pytz]
   ----------------------------------------  0/51 [pytz]
   ----------------------------------------  0/51 [pytz]
   ----------------------------------------  0/51 [pytz]
   ----------------------------------------  0/51 [pytz]
    ---------------------------------------  1/51 [urllib3]
    ---------------------------------------  1/51 [urllib3]
    ---------------------------------------  1/51 [urllib3]
    ---------------------------------------  1/51 [urllib3]
    ---------------------------------------  1/51 [urllib3]
    ---------------------------------------  1/51 [urllib3]
    ---------------------------------------  1/51 [urllib3]
    ---------------------------------------  1/51 [urllib3]
    ---------------------------------------  1/51 [urllib3]
    ---------------------------------------  1/51 [urllib3]
   - --------------------------------------  2/51 [tzdata]
   - --------------------------------------  2/51 [tzdata]
   - --------------------------------------  2/51 [tzdata]
   - --------------------------------------  2/51 [tzdata]
   - --------------------------------------  2/51 [tzdata]
   - --------------------------------------  2/51 [tzdata]
   - --------------------------------------  2/51 [tzdata]
   -- -------------------------------------  3/51 [toolz]
   -- -------------------------------------  3/51 [toolz]
   -- -------------------------------------  3/51 [toolz]
   -- -------------------------------------  3/51 [toolz]
   -- -------------------------------------  3/51 [toolz]
   -- -------------------------------------  3/51 [toolz]
   -- -------------------------------------  3/51 [toolz]
   -- -------------------------------------  3/51 [toolz]
   -- -------------------------------------  3/51 [toolz]
   --- ------------------------------------  5/51 [rainflow]
   ---- -----------------------------------  6/51 [pyyaml]
   ---- -----------------------------------  6/51 [pyyaml]
   ---- -----------------------------------  6/51 [pyyaml]
   ---- -----------------------------------  6/51 [pyyaml]
   ----- ----------------------------------  7/51 [pyparsing]
   ----- ----------------------------------  7/51 [pyparsing]
   ----- ----------------------------------  7/51 [pyparsing]
   ----- ----------------------------------  7/51 [pyparsing]
   ----- ----------------------------------  7/51 [pyparsing]
   ------ ---------------------------------  8/51 [pillow]
   ------ ---------------------------------  8/51 [pillow]
   ------ ---------------------------------  8/51 [pillow]
   ------ ---------------------------------  8/51 [pillow]
   ------ ---------------------------------  8/51 [pillow]
   ------ ---------------------------------  8/51 [pillow]
   ------ ---------------------------------  8/51 [pillow]
   ------ ---------------------------------  8/51 [pillow]
   ------ ---------------------------------  8/51 [pillow]
   ------ ---------------------------------  8/51 [pillow]
   ------ ---------------------------------  8/51 [pillow]
   ------ ---------------------------------  8/51 [pillow]
   ------ ---------------------------------  8/51 [pillow]
   ------ ---------------------------------  8/51 [pillow]
   ------ ---------------------------------  8/51 [pillow]
   ------ ---------------------------------  8/51 [pillow]
   ------ ---------------------------------  8/51 [pillow]
   ------ ---------------------------------  8/51 [pillow]
   ------ ---------------------------------  8/51 [pillow]
   ------ ---------------------------------  8/51 [pillow]
   ------ ---------------------------------  8/51 [pillow]
   ------ ---------------------------------  8/51 [pillow]
   ------ ---------------------------------  8/51 [pillow]
   ------ ---------------------------------  8/51 [pillow]
   ------ ---------------------------------  8/51 [pillow]
   ------ ---------------------------------  8/51 [pillow]
   ------ ---------------------------------  8/51 [pillow]
   ------- --------------------------------  9/51 [numpy]
   ------- --------------------------------  9/51 [numpy]
   ------- --------------------------------  9/51 [numpy]
   ------- --------------------------------  9/51 [numpy]
   ------- --------------------------------  9/51 [numpy]
   ------- --------------------------------  9/51 [numpy]
   ------- --------------------------------  9/51 [numpy]
   ------- --------------------------------  9/51 [numpy]
   ------- --------------------------------  9/51 [numpy]
   ------- --------------------------------  9/51 [numpy]
   ------- --------------------------------  9/51 [numpy]
   ------- --------------------------------  9/51 [numpy]
   ------- --------------------------------  9/51 [numpy]
   ------- --------------------------------  9/51 [numpy]
   ------- --------------------------------  9/51 [numpy]
   ------- --------------------------------  9/51 [numpy]
   ------- --------------------------------  9/51 [numpy]
   ------- --------------------------------  9/51 [numpy]
   ------- --------------------------------  9/51 [numpy]
   ------- --------------------------------  9/51 [numpy]
   ------- --------------------------------  9/51 [numpy]
   ------- --------------------------------  9/51 [numpy]
   ------- --------------------------------  9/51 [numpy]
   ------- --------------------------------  9/51 [numpy]
   ------- --------------------------------  9/51 [numpy]
   ------- --------------------------------  9/51 [numpy]
   ------- --------------------------------  9/51 [numpy]
   ------- --------------------------------  9/51 [numpy]
   ------- --------------------------------  9/51 [numpy]
   ------- --------------------------------  9/51 [numpy]
   ------- --------------------------------  9/51 [numpy]
   ------- --------------------------------  9/51 [numpy]
   ------- --------------------------------  9/51 [numpy]
   ------- --------------------------------  9/51 [numpy]
   ------- --------------------------------  9/51 [numpy]
   ------- --------------------------------  9/51 [numpy]
   ------- --------------------------------  9/51 [numpy]
   ------- --------------------------------  9/51 [numpy]
   ------- --------------------------------  9/51 [numpy]
   ------- --------------------------------  9/51 [numpy]
   ------- --------------------------------  9/51 [numpy]
   ------- --------------------------------  9/51 [numpy]
   ------- --------------------------------  9/51 [numpy]
   ------- --------------------------------  9/51 [numpy]
   ------- --------------------------------  9/51 [numpy]
   ------- --------------------------------  9/51 [numpy]
   ------- --------------------------------  9/51 [numpy]
   ------- --------------------------------  9/51 [numpy]
   ------- --------------------------------  9/51 [numpy]
   ------- --------------------------------  9/51 [numpy]
   ------- --------------------------------  9/51 [numpy]
   ------- --------------------------------  9/51 [numpy]
   ------- --------------------------------  9/51 [numpy]

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [16]:

examples_sites = pd.read_csv(f'{examples_filepath}examples_sites.csv', index_col=0, sep=',')
examples_sites

,case,name,longitude,latitude,altitude,input_ts_fn,sim_pars_fn,price_fn,price_col,H2_demand_col
0,India,Indian_site_good_wind,77.500226,8.334294,679.803454,India/GWA3/input_ts_Indian_site_good_wind.csv,India/hpp_pars.yml,India/Indian_elec_price_t.csv,Price,India/H2_demand.csv
1,India,Indian_site_good_solar,68.542204,23.542099,29.883557,India/GWA3/input_ts_Indian_site_good_solar.csv,India/hpp_pars.yml,India/Indian_elec_price_t.csv,Price,India/H2_demand.csv
2,India,Indian_site_bad_solar_bad_wind,77.916878,17.292316,627.424643,India/GWA3/input_ts_Indian_site_bad_solar_bad_...,India/hpp_pars.yml,India/Indian_elec_price_t.csv,Price,India/H2_demand.csv
3,Europe,France_good_solar,4.229736,44.422011,204.000000,Europe/GWA3/input_ts_France_good_solar.csv,Europe/hpp_pars.yml,Europe/2030-EL_PRICE.csv,FR_R,Europe/H2_demand.csv
4,Europe,France_good_wind,-0.864258,48.744116,302.000000,Europe/GWA3/input_ts_France_good_wind.csv,Europe/hpp_pars.yml,Europe/2030-EL_PRICE.csv,FR_R,Europe/H2_demand.csv
5,Europe,France_bad_solar_n_wind,2.167969,47.428087,140.000000,Europe/GWA3/input_ts_France_bad_solar_n_wind.csv,Europe/hpp_pars.yml,Europe/2030-EL_PRICE.csv,FR_R,Europe/H2_demand.csv
6,Europe,Germany_bad_solar_n_wind,10.766602,49.310798,442.000000,Europe/GWA3/input_ts_Germany_bad_solar_n_wind.csv,Europe/hpp_pars.yml,Europe/2030-EL_PRICE.csv,DE_ME,Europe/H2_demand.csv
7,Europe,Germany_good_wind,7.873535,53.287111,5.000000,Europe/GWA3/input_ts_Germany_good_wind.csv,Europe/hpp_pars.yml,Europe/2030-EL_PRICE.csv,DE_NW,Europe/H2_demand.csv
8,Europe,Denmark_good_solar,11.813965,55.397760,42.000000,Europe/GWA3/input_ts_Denmark_good_solar.csv,Europe/hpp_pars.yml,Europe/2030-EL_PRICE.csv,DK_E,Europe/H2_demand.csv
9,Europe,Denmark_good_wind,8.594398,56.227322,85.000000,Europe/GWA3/input_ts_Denmark_good_wind.csv,Europe/hpp_pars.yml,Europe/2030-EL_PRICE.csv,DK_W,Europe/H2_demand.csv

In [12]:
print(examples_sites.columns.tolist())
print(examples_sites.head(2))

[]
Empty DataFrame
Columns: []
Index: [0,India,Indian_site_good_wind,77.50022583,8.334293917,679.803454,India/GWA3/input_ts_Indian_site_good_wind.csv,India/hpp_pars.yml,India/Indian_elec_price_t.csv,Price,India/H2_demand.csv, 1,India,Indian_site_good_solar,68.54220353,23.54209921,29.88355741,India/GWA3/input_ts_Indian_site_good_solar.csv,India/hpp_pars.yml,India/Indian_elec_price_t.csv,Price,India/H2_demand.csv]

In [17]:
name = 'France_good_wind'
ex_site = examples_sites.loc[examples_sites.name == name]

longitude = ex_site['longitude'].values[0]
latitude = ex_site['latitude'].values[0]
altitude = ex_site['altitude'].values[0]

In [18]:
input_ts_fn = examples_filepath+ex_site['input_ts_fn'].values[0]

input_ts = pd.read_csv(input_ts_fn, index_col=0, parse_dates=True)

required_cols = [col for col in input_ts.columns if 'WD' not in col]
input_ts = input_ts.loc[:,required_cols]
input_ts

,WS_1,WS_50,WS_100,WS_150,WS_200,temp_air_1,ghi,dni,dhi,Price
2012-01-01 00:00:00,5.031528,11.491562,13.293840,15.697655,16.581168,284.873662,0.10670,0.0,0.10670,32.685
2012-01-01 01:00:00,4.527461,10.535852,12.225673,14.449516,15.304116,284.759079,0.05335,0.0,0.05335,32.685
2012-01-01 02:00:00,4.485136,10.576099,12.302628,14.711214,15.679654,284.682409,0.00000,0.0,0.00000,32.685
2012-01-01 03:00:00,4.684235,10.943120,12.708081,15.154307,16.165412,284.804835,0.00000,0.0,0.00000,32.685
2012-01-01 04:00:00,4.698410,11.066226,12.869864,15.381294,16.433400,284.912742,0.00000,0.0,0.00000,32.685
...,...,...,...,...,...,...,...,...,...,...
2012-12-31 19:00:00,6.927975,15.510276,17.877532,19.361598,21.069684,281.919356,0.00000,0.0,0.00000,37.591
2012-12-31 20:00:00,6.355326,14.262557,16.448514,17.822397,19.521058,281.790435,0.00000,0.0,0.00000,35.839
2012-12-31 21:00:00,5.456462,12.476146,14.429818,15.918705,17.597519,281.700990,0.00000,0.0,0.00000,35.362
2012-12-31 22:00:00,4.000478,9.516692,11.088230,12.442577,13.866160,281.499113,0.00000,0.0,0.00000,34.468
2012-12-31 23:00:00,3.073095,7.789771,9.176926,10.399925,11.612548,281.450042,0.00000,0.0,0.00000,33.417

In [19]:
sim_pars_fn = examples_filepath+ex_site['sim_pars_fn'].values[0]

with open(sim_pars_fn) as file:
    sim_pars = yaml.load(file, Loader=yaml.FullLoader)

print(sim_pars_fn)
sim_pars

c:/Users/ntagkrasd/emerge_benchmarking/venv/Lib/site-packages/hydesign/examples/Europe/hpp_pars.yml

{'G_MW': 300,
 'year': '2012',
 'N_life': 25,
 'wind_turbine_cost': 640000,
 'wind_civil_works_cost': 260000,
 'wind_fixed_onm_cost': 12600,
 'wind_variable_onm_cost': 1.35,
 'd_ref': 145,
 'hh_ref': 100,
 'p_rated_ref': 5.0,
 'wpp_efficiency': 1,
 'wind_deg_yr': [0, 25],
 'wind_deg': [0, 0.25],
 'share_WT_deg_types': 0.5,
 'solar_PV_cost': 110000,
 'solar_hardware_installation_cost': 100000,
 'solar_inverter_cost': 20000,
 'solar_fixed_onm_cost': 4500,
 'land_use_per_solar_MW': 0.01226,
 'tracking': 'No',
 'pv_deg_yr': [0, 1, 25],
 'pv_deg': [0.03, 0.03, 0.28],
 'battery_energy_cost': 45000,
 'battery_power_cost': 16000,
 'battery_BOP_installation_commissioning_cost': 18000,
 'battery_control_system_cost': 4500,
 'battery_energy_onm_cost': 0,
 'battery_depth_of_discharge': 0.9,
 'battery_charge_efficiency': 0.98,
 'battery_price_reduction_per_year': 0.1,
 'min_LoH': 0.7,
 'n_full_power_hours_expected_per_day_at_peak_price': 0,
 'peak_hr_quantile': 0.9,
 'price_H2': 5,
 'storage_eff': 0.9,
 'ptg_deg': 0.99,
 'hhv': 39.3,
 'water_consumption': 9.4,
 'electrolyzer_capex_cost': 480000,
 'electrolyzer_opex_cost': 9600,
 'electrolyzer_power_electronics_cost': 0,
 'water_cost': 4,
 'water_treatment_cost': 2,
 'H2_storage_capex_cost': 300,
 'H2_storage_opex_cost': 3,
 'H2_transportation_cost': 5,
 'H2_transportation_distance': 0,
 'penalty_factor_H2': 0.5,
 'electrolyzer_eff_curve_name': 'PEM electrolyzer simple',
 'min_power_standby': 0.1,
 'ramp_up_limit': 50,
 'ramp_down_limit': 50,
 'hpp_BOS_soft_cost': 119940,
 'hpp_grid_connection_cost': 50000,
 'land_cost': 300000,
 'wind_WACC': 0.052,
 'solar_WACC': 0.048,
 'battery_WACC': 0.08,
 'tax_rate': 0.22,
 'ptg_WACC': 0.07,
 'phasing_yr': [-1, 0],
 'phasing_CAPEX': [1, 1],
 'inflation_yr': [-3, 0, 1, 25],
 'inflation': [0.1, 0.1, 0.06, 0.06],
 'ref_yr_inflation': 0,
 'depreciation_yr': [0, 25],
 'depreciation': [0, 1],
 'era5_zarr': '/groups/reanalyses/era5/app/era5.zarr',
 'ratio_gwa_era5': '/groups/INP/era5/ratio_gwa2_era5.nc',
 'era5_ghi_zarr': '/groups/INP/era5/ghi.zarr',
 'elevation_fn': '/groups/INP/era5/SRTMv3_plus_ViewFinder_coarsen.nc'}

In [20]:
rotor_diameter_m = 220
hub_height_m = 130
wt_rated_power_MW = 10
surface_tilt_deg = 35
surface_azimuth_deg = 180
DC_AC_ratio = 1.5

In [21]:
hpp = hpp_model(
        latitude=latitude,
        longitude=longitude,
        altitude=altitude,
        rotor_diameter_m = rotor_diameter_m,
        hub_height_m = hub_height_m,
        wt_rated_power_MW = wt_rated_power_MW,
        surface_tilt_deg = surface_tilt_deg,
        surface_azimuth_deg = surface_azimuth_deg,
        DC_AC_ratio = DC_AC_ratio,
        num_batteries = 5,
        work_dir = './',
        sim_pars_fn = sim_pars_fn,
        input_ts_fn = input_ts_fn,
)

Fixed parameters on the site
-------------------------------
longitude = -0.864258
latitude = 48.744116
altitude = 302.0