In [3]:
import importlib
import os
import time
!pip install hydesign
import yaml
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from hydesign.assembly.hpp_assembly import hpp_model
from hydesign.examples import examples_filepath

Collecting hydesign
  Using cached hydesign-1.6.0-py3-none-any.whl.metadata (4.9 kB)
Requirement already satisfied: numpy>=2 in C:\Users\dhmht\miniconda3\envs\hydesign\Lib\site-packages (from hydesign) (2.4.2)
Collecting pandas (from hydesign)
  Downloading pandas-3.0.1-cp311-cp311-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: scipy in C:\Users\dhmht\miniconda3\envs\hydesign\Lib\site-packages (from hydesign) (1.17.0)
Collecting h5netcdf (from hydesign)
  Using cached h5netcdf-1.8.1-py3-none-any.whl.metadata (15 kB)
Collecting netcdf4 (from hydesign)
  Downloading netcdf4-1.7.4-cp311-abi3-win_amd64.whl.metadata (2.1 kB)
Collecting xarray (from hydesign)
  Downloading xarray-2026.2.0-py3-none-any.whl.metadata (12 kB)
Collecting openmdao (from hydesign)
  Using cached openmdao-3.42.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: smt==2.9.2 in C:\Users\dhmht\miniconda3\envs\hydesign\Lib\site-packages (from hydesign) (2.9.2)
Collecting cplex (from hydesign)
  Downloading cplex-22.1.2.0-cp311-cp311-win_amd64.whl.metadata (56 kB)
Collecting docplex (from hydesign)
  Using cached docplex-2.31.254.tar.gz (647 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting numpy-financial (from hydesign)
  Using cached numpy_financial-1.0.0-py3-none-any.whl.metadata (2.2 kB)
Collecting pvlib (from hydesign)
  Using cached pvlib-0.15.0-py3-none-any.whl.metadata (2.9 kB)
Collecting statsmodels (from hydesign)
  Downloading statsmodels-0.14.6-cp311-cp311-win_amd64.whl.metadata (9.8 kB)
Collecting rainflow (from hydesign)
  Using cached rainflow-3.2.0-py3-none-any.whl.metadata (3.6 kB)
Collecting pyyaml (from hydesign)
  Downloading pyyaml-6.0.3-cp311-cp311-win_amd64.whl.metadata (2.4 kB)
Requirement already satisfied: matplotlib in C:\Users\dhmht\miniconda3\envs\hydesign\Lib\site-packages (from hydesign) (3.10.8)
Collecting ortools (from hydesign)
  Downloading ortools-9.15.6755-cp311-cp311-win_amd64.whl.metadata (3.2 kB)
Collecting NREL-PySAM (from hydesign)
  Downloading NREL_PySAM-7.1.0-cp311-cp311-win_amd64.whl.metadata (9.0 kB)
Collecting tqdm (from hydesign)
  Downloading tqdm-4.67.3-py3-none-any.whl.metadata (57 kB)
Collecting h5py>=3.13 (from hydesign)
  Downloading h5py-3.15.1-cp311-cp311-win_amd64.whl.metadata (3.1 kB)
Requirement already satisfied: packaging in C:\Users\dhmht\miniconda3\envs\hydesign\Lib\site-packages (from smt==2.9.2->hydesign) (26.0)
Requirement already satisfied: scikit-learn in C:\Users\dhmht\miniconda3\envs\hydesign\Lib\site-packages (from smt==2.9.2->hydesign) (1.8.0)
Requirement already satisfied: pyDOE3 in C:\Users\dhmht\miniconda3\envs\hydesign\Lib\site-packages (from smt==2.9.2->hydesign) (1.6.2)
Requirement already satisfied: jenn in C:\Users\dhmht\miniconda3\envs\hydesign\Lib\site-packages (from smt==2.9.2->hydesign) (2.0.0)
Requirement already satisfied: six in C:\Users\dhmht\miniconda3\envs\hydesign\Lib\site-packages (from docplex->hydesign) (1.17.0)
Requirement already satisfied: jsonpointer in C:\Users\dhmht\miniconda3\envs\hydesign\Lib\site-packages (from jenn->smt==2.9.2->hydesign) (3.0.0)
Requirement already satisfied: jsonschema in C:\Users\dhmht\miniconda3\envs\hydesign\Lib\site-packages (from jenn->smt==2.9.2->hydesign) (4.26.0)
Requirement already satisfied: orjson in C:\Users\dhmht\miniconda3\envs\hydesign\Lib\site-packages (from jenn->smt==2.9.2->hydesign) (3.11.5)
Requirement already satisfied: attrs>=22.2.0 in C:\Users\dhmht\miniconda3\envs\hydesign\Lib\site-packages (from jsonschema->jenn->smt==2.9.2->hydesign) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in C:\Users\dhmht\miniconda3\envs\hydesign\Lib\site-packages (from jsonschema->jenn->smt==2.9.2->hydesign) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in C:\Users\dhmht\miniconda3\envs\hydesign\Lib\site-packages (from jsonschema->jenn->smt==2.9.2->hydesign) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in C:\Users\dhmht\miniconda3\envs\hydesign\Lib\site-packages (from jsonschema->jenn->smt==2.9.2->hydesign) (0.30.0)
Requirement already satisfied: typing-extensions>=4.4.0 in C:\Users\dhmht\miniconda3\envs\hydesign\Lib\site-packages (from referencing>=0.28.4->jsonschema->jenn->smt==2.9.2->hydesign) (4.15.0)
Requirement already satisfied: contourpy>=1.0.1 in C:\Users\dhmht\miniconda3\envs\hydesign\Lib\site-packages (from matplotlib->hydesign) (1.3.3)
Requirement already satisfied: cycler>=0.10 in C:\Users\dhmht\miniconda3\envs\hydesign\Lib\site-packages (from matplotlib->hydesign) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in C:\Users\dhmht\miniconda3\envs\hydesign\Lib\site-packages (from matplotlib->hydesign) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in C:\Users\dhmht\miniconda3\envs\hydesign\Lib\site-packages (from matplotlib->hydesign) (1.4.9)
Requirement already satisfied: pillow>=8 in C:\Users\dhmht\miniconda3\envs\hydesign\Lib\site-packages (from matplotlib->hydesign) (12.1.1)
Requirement already satisfied: pyparsing>=3 in C:\Users\dhmht\miniconda3\envs\hydesign\Lib\site-packages (from matplotlib->hydesign) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in C:\Users\dhmht\miniconda3\envs\hydesign\Lib\site-packages (from matplotlib->hydesign) (2.9.0.post0)
Collecting cftime (from netcdf4->hydesign)
  Downloading cftime-1.6.5-cp311-cp311-win_amd64.whl.metadata (8.8 kB)
Collecting certifi (from netcdf4->hydesign)
  Using cached certifi-2026.1.4-py3-none-any.whl.metadata (2.5 kB)
Collecting networkx>=3.3 (from openmdao->hydesign)
  Downloading networkx-3.6.1-py3-none-any.whl.metadata (6.8 kB)
Collecting requests (from openmdao->hydesign)
  Using cached requests-2.32.5-py3-none-any.whl.metadata (4.9 kB)
Collecting absl-py>=2.0.0 (from ortools->hydesign)
  Downloading absl_py-2.4.0-py3-none-any.whl.metadata (3.3 kB)
Collecting protobuf<6.34,>=6.33.1 (from ortools->hydesign)
  Using cached protobuf-6.33.5-cp310-abi3-win_amd64.whl.metadata (593 bytes)
Collecting immutabledict>=3.0.0 (from ortools->hydesign)
  Using cached immutabledict-4.3.1-py3-none-any.whl.metadata (3.5 kB)
Collecting tzdata (from pandas->hydesign)
  Downloading tzdata-2025.3-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting pytz (from pvlib->hydesign)
  Using cached pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting charset_normalizer<4,>=2 (from requests->openmdao->hydesign)
  Downloading charset_normalizer-3.4.4-cp311-cp311-win_amd64.whl.metadata (38 kB)
Collecting idna<4,>=2.5 (from requests->openmdao->hydesign)
  Using cached idna-3.11-py3-none-any.whl.metadata (8.4 kB)
Collecting urllib3<3,>=1.21.1 (from requests->openmdao->hydesign)
  Using cached urllib3-2.6.3-py3-none-any.whl.metadata (6.9 kB)
Requirement already satisfied: joblib>=1.3.0 in C:\Users\dhmht\miniconda3\envs\hydesign\Lib\site-packages (from scikit-learn->smt==2.9.2->hydesign) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in C:\Users\dhmht\miniconda3\envs\hydesign\Lib\site-packages (from scikit-learn->smt==2.9.2->hydesign) (3.6.0)
Collecting patsy>=0.5.6 (from statsmodels->hydesign)
  Downloading patsy-1.0.2-py2.py3-none-any.whl.metadata (3.6 kB)
Requirement already satisfied: colorama in C:\Users\dhmht\miniconda3\envs\hydesign\Lib\site-packages (from tqdm->hydesign) (0.4.6)
Using cached hydesign-1.6.0-py3-none-any.whl (88.6 MB)
Downloading h5py-3.15.1-cp311-cp311-win_amd64.whl (2.9 MB)
   ---------------------------------------- 0.0/2.9 MB ? eta -:--:--
   ---------- ----------------------------- 0.8/2.9 MB 4.8 MB/s eta 0:00:01
   --------------------- ------------------ 1.6/2.9 MB 4.9 MB/s eta 0:00:01
   ------------------------------------ --- 2.6/2.9 MB 4.9 MB/s eta 0:00:01
   ---------------------------------------- 2.9/2.9 MB 4.9 MB/s  0:00:00
Downloading cplex-22.1.2.0-cp311-cp311-win_amd64.whl (26.4 MB)
   ---------------------------------------- 0.0/26.4 MB ? eta -:--:--
   - -------------------------------------- 0.8/26.4 MB 3.7 MB/s eta 0:00:07
   -- ------------------------------------- 1.8/26.4 MB 4.8 MB/s eta 0:00:06
   --- ------------------------------------ 2.6/26.4 MB 4.7 MB/s eta 0:00:06
   ----- ---------------------------------- 3.7/26.4 MB 4.7 MB/s eta 0:00:05
   ------- -------------------------------- 4.7/26.4 MB 4.6 MB/s eta 0:00:05
   -------- ------------------------------- 5.5/26.4 MB 4.4 MB/s eta 0:00:05
   --------- ------------------------------ 6.6/26.4 MB 4.6 MB/s eta 0:00:05
   ----------- ---------------------------- 7.6/26.4 MB 4.7 MB/s eta 0:00:04
   ------------- -------------------------- 8.9/26.4 MB 4.8 MB/s eta 0:00:04
   --------------- ------------------------ 10.0/26.4 MB 4.8 MB/s eta 0:00:04
   ---------------- ----------------------- 10.7/26.4 MB 4.8 MB/s eta 0:00:04
   ----------------- ---------------------- 11.8/26.4 MB 4.8 MB/s eta 0:00:04
   ------------------- -------------------- 12.8/26.4 MB 4.8 MB/s eta 0:00:03
   --------------------- ------------------ 13.9/26.4 MB 4.8 MB/s eta 0:00:03
   ---------------------- ----------------- 14.9/26.4 MB 4.8 MB/s eta 0:00:03
   ----------------------- ---------------- 15.7/26.4 MB 4.8 MB/s eta 0:00:03
   ------------------------- -------------- 16.8/26.4 MB 4.8 MB/s eta 0:00:03
   -------------------------- ------------- 17.6/26.4 MB 4.7 MB/s eta 0:00:02
   --------------------------- ------------ 18.1/26.4 MB 4.6 MB/s eta 0:00:02
   ----------------------------- ---------- 19.1/26.4 MB 4.6 MB/s eta 0:00:02
   ------------------------------ --------- 20.2/26.4 MB 4.7 MB/s eta 0:00:02
   -------------------------------- ------- 21.2/26.4 MB 4.6 MB/s eta 0:00:02
   --------------------------------- ------ 22.0/26.4 MB 4.6 MB/s eta 0:00:01
   ---------------------------------- ----- 23.1/26.4 MB 4.6 MB/s eta 0:00:01
   ------------------------------------ --- 23.9/26.4 MB 4.6 MB/s eta 0:00:01
   ------------------------------------- -- 24.9/26.4 MB 4.6 MB/s eta 0:00:01
   -------------------------------------- - 25.4/26.4 MB 4.5 MB/s eta 0:00:01
   ---------------------------------------- 26.4/26.4 MB 4.5 MB/s  0:00:05
Using cached h5netcdf-1.8.1-py3-none-any.whl (62 kB)
Downloading netcdf4-1.7.4-cp311-abi3-win_amd64.whl (21.3 MB)
   ---------------------------------------- 0.0/21.3 MB ? eta -:--:--
   - -------------------------------------- 0.8/21.3 MB 4.2 MB/s eta 0:00:05
   -- ------------------------------------- 1.6/21.3 MB 4.2 MB/s eta 0:00:05
   ---- ----------------------------------- 2.4/21.3 MB 4.1 MB/s eta 0:00:05
   ----- ---------------------------------- 2.9/21.3 MB 3.4 MB/s eta 0:00:06
   ----- ---------------------------------- 3.1/21.3 MB 3.4 MB/s eta 0:00:06
   ------ --------------------------------- 3.4/21.3 MB 3.1 MB/s eta 0:00:06
   ------- -------------------------------- 3.9/21.3 MB 2.6 MB/s eta 0:00:07
   ------- -------------------------------- 4.2/21.3 MB 2.6 MB/s eta 0:00:07
   ------- -------------------------------- 4.2/21.3 MB 2.6 MB/s eta 0:00:07
   -------- ------------------------------- 4.7/21.3 MB 2.3 MB/s eta 0:00:08
   --------- ------------------------------ 5.0/21.3 MB 2.2 MB/s eta 0:00:08
   --------- ------------------------------ 5.2/21.3 MB 2.1 MB/s eta 0:00:08
   ---------- ----------------------------- 5.5/21.3 MB 2.1 MB/s eta 0:00:08
   ---------- ----------------------------- 5.8/21.3 MB 1.9 MB/s eta 0:00:09
   ----------- ---------------------------- 6.0/21.3 MB 1.9 MB/s eta 0:00:08
   ----------- ---------------------------- 6.0/21.3 MB 1.9 MB/s eta 0:00:08
   ------------ --------------------------- 6.6/21.3 MB 1.8 MB/s eta 0:00:09
   ------------ --------------------------- 6.6/21.3 MB 1.8 MB/s eta 0:00:09
   ------------- -------------------------- 7.3/21.3 MB 1.8 MB/s eta 0:00:08
   --------------- ------------------------ 8.1/21.3 MB 1.9 MB/s eta 0:00:07
   ---------------- ----------------------- 8.7/21.3 MB 2.0 MB/s eta 0:00:07
   ----------------- ---------------------- 9.2/21.3 MB 2.0 MB/s eta 0:00:07
   ----------------- ---------------------- 9.4/21.3 MB 2.0 MB/s eta 0:00:06
   ------------------ --------------------- 10.0/21.3 MB 2.0 MB/s eta 0:00:06
   -------------------- ------------------- 10.7/21.3 MB 2.1 MB/s eta 0:00:06
   --------------------- ------------------ 11.3/21.3 MB 2.1 MB/s eta 0:00:05
   ---------------------- ----------------- 11.8/21.3 MB 2.1 MB/s eta 0:00:05
   ----------------------- ---------------- 12.6/21.3 MB 2.1 MB/s eta 0:00:05
   ------------------------- -------------- 13.4/21.3 MB 2.2 MB/s eta 0:00:04
   -------------------------- ------------- 13.9/21.3 MB 2.2 MB/s eta 0:00:04
   --------------------------- ------------ 14.4/21.3 MB 2.2 MB/s eta 0:00:04
   ---------------------------- ----------- 15.2/21.3 MB 2.3 MB/s eta 0:00:03
   ----------------------------- ---------- 15.7/21.3 MB 2.3 MB/s eta 0:00:03
   ------------------------------- -------- 16.5/21.3 MB 2.3 MB/s eta 0:00:03
   -------------------------------- ------- 17.3/21.3 MB 2.4 MB/s eta 0:00:02
   --------------------------------- ------ 18.1/21.3 MB 2.4 MB/s eta 0:00:02
   ---------------------------------- ----- 18.6/21.3 MB 2.4 MB/s eta 0:00:02
   ------------------------------------ --- 19.4/21.3 MB 2.5 MB/s eta 0:00:01
   ------------------------------------- -- 19.9/21.3 MB 2.5 MB/s eta 0:00:01
   -------------------------------------- - 20.7/21.3 MB 2.5 MB/s eta 0:00:01
   ---------------------------------------- 21.3/21.3 MB 2.5 MB/s  0:00:08
Using cached certifi-2026.1.4-py3-none-any.whl (152 kB)
Downloading cftime-1.6.5-cp311-cp311-win_amd64.whl (473 kB)
Downloading NREL_PySAM-7.1.0-cp311-cp311-win_amd64.whl (32.8 MB)
   ---------------------------------------- 0.0/32.8 MB ? eta -:--:--
    --------------------------------------- 0.5/32.8 MB 3.4 MB/s eta 0:00:10
   - -------------------------------------- 1.3/32.8 MB 3.5 MB/s eta 0:00:09
   -- ------------------------------------- 1.8/32.8 MB 3.5 MB/s eta 0:00:09
   --- ------------------------------------ 2.6/32.8 MB 3.4 MB/s eta 0:00:10
   ---- ----------------------------------- 3.4/32.8 MB 3.5 MB/s eta 0:00:09
   ---- ----------------------------------- 3.9/32.8 MB 3.3 MB/s eta 0:00:09
   ----- ---------------------------------- 4.5/32.8 MB 3.4 MB/s eta 0:00:09
   ------ --------------------------------- 5.2/32.8 MB 3.3 MB/s eta 0:00:09
   ------- -------------------------------- 5.8/32.8 MB 3.2 MB/s eta 0:00:09
   ------- -------------------------------- 6.3/32.8 MB 3.2 MB/s eta 0:00:09
   -------- ------------------------------- 7.1/32.8 MB 3.2 MB/s eta 0:00:09
   -------- ------------------------------- 7.3/32.8 MB 3.0 MB/s eta 0:00:09
   --------- ------------------------------ 7.6/32.8 MB 2.9 MB/s eta 0:00:09
   ---------- ----------------------------- 8.4/32.8 MB 2.9 MB/s eta 0:00:09
   ---------- ----------------------------- 8.9/32.8 MB 2.9 MB/s eta 0:00:09
   ----------- ---------------------------- 9.4/32.8 MB 2.9 MB/s eta 0:00:09
   ------------ --------------------------- 10.0/32.8 MB 2.9 MB/s eta 0:00:08
   ------------ --------------------------- 10.5/32.8 MB 2.8 MB/s eta 0:00:08
   ------------- -------------------------- 11.0/32.8 MB 2.8 MB/s eta 0:00:08
   ------------- -------------------------- 11.0/32.8 MB 2.8 MB/s eta 0:00:08
   ------------- -------------------------- 11.3/32.8 MB 2.6 MB/s eta 0:00:09
   ------------- -------------------------- 11.3/32.8 MB 2.6 MB/s eta 0:00:09
   ------------- -------------------------- 11.3/32.8 MB 2.6 MB/s eta 0:00:09
   -------------- ------------------------- 11.5/32.8 MB 2.4 MB/s eta 0:00:09
   -------------- ------------------------- 11.8/32.8 MB 2.3 MB/s eta 0:00:10
   -------------- ------------------------- 11.8/32.8 MB 2.3 MB/s eta 0:00:10
   -------------- ------------------------- 12.1/32.8 MB 2.2 MB/s eta 0:00:10
   --------------- ------------------------ 12.3/32.8 MB 2.1 MB/s eta 0:00:10
   --------------- ------------------------ 12.6/32.8 MB 2.1 MB/s eta 0:00:10
   --------------- ------------------------ 12.8/32.8 MB 2.1 MB/s eta 0:00:10
   --------------- ------------------------ 13.1/32.8 MB 2.1 MB/s eta 0:00:10
   ---------------- ----------------------- 13.4/32.8 MB 2.0 MB/s eta 0:00:10
   ---------------- ----------------------- 13.6/32.8 MB 2.0 MB/s eta 0:00:10
   ----------------- ---------------------- 14.2/32.8 MB 2.0 MB/s eta 0:00:10
   ----------------- ---------------------- 14.4/32.8 MB 2.0 MB/s eta 0:00:10
   ------------------ --------------------- 14.9/32.8 MB 2.0 MB/s eta 0:00:09
   ------------------- -------------------- 15.7/32.8 MB 2.0 MB/s eta 0:00:09
   ------------------- -------------------- 16.0/32.8 MB 2.1 MB/s eta 0:00:09
   -------------------- ------------------- 16.5/32.8 MB 2.0 MB/s eta 0:00:09
   --------------------- ------------------ 17.3/32.8 MB 2.1 MB/s eta 0:00:08
   --------------------- ------------------ 17.6/32.8 MB 2.1 MB/s eta 0:00:08
   ---------------------- ----------------- 18.1/32.8 MB 2.1 MB/s eta 0:00:08
   ---------------------- ----------------- 18.6/32.8 MB 2.1 MB/s eta 0:00:07
   ----------------------- ---------------- 19.1/32.8 MB 2.1 MB/s eta 0:00:07
   ----------------------- ---------------- 19.7/32.8 MB 2.1 MB/s eta 0:00:07
   ------------------------- -------------- 20.7/32.8 MB 2.2 MB/s eta 0:00:06
   ------------------------- -------------- 21.2/32.8 MB 2.2 MB/s eta 0:00:06
   -------------------------- ------------- 21.8/32.8 MB 2.2 MB/s eta 0:00:06
   --------------------------- ------------ 22.5/32.8 MB 2.2 MB/s eta 0:00:05
   ---------------------------- ----------- 23.1/32.8 MB 2.2 MB/s eta 0:00:05
   ---------------------------- ----------- 23.3/32.8 MB 2.2 MB/s eta 0:00:05
   ----------------------------- ---------- 23.9/32.8 MB 2.2 MB/s eta 0:00:05
   ----------------------------- ---------- 24.4/32.8 MB 2.2 MB/s eta 0:00:04
   ------------------------------ --------- 24.9/32.8 MB 2.2 MB/s eta 0:00:04
   ------------------------------- -------- 25.7/32.8 MB 2.3 MB/s eta 0:00:04
   ------------------------------- -------- 26.2/32.8 MB 2.3 MB/s eta 0:00:03
   -------------------------------- ------- 26.7/32.8 MB 2.3 MB/s eta 0:00:03
   --------------------------------- ------ 27.5/32.8 MB 2.3 MB/s eta 0:00:03
   ---------------------------------- ----- 28.3/32.8 MB 2.3 MB/s eta 0:00:02
   ----------------------------------- ---- 29.1/32.8 MB 2.3 MB/s eta 0:00:02
   ------------------------------------ --- 29.9/32.8 MB 2.4 MB/s eta 0:00:02
   ------------------------------------- -- 30.7/32.8 MB 2.4 MB/s eta 0:00:01
   ------------------------------------- -- 31.2/32.8 MB 2.4 MB/s eta 0:00:01
   -------------------------------------- - 31.5/32.8 MB 2.4 MB/s eta 0:00:01
   -------------------------------------- - 31.7/32.8 MB 2.4 MB/s eta 0:00:01
   ---------------------------------------  32.5/32.8 MB 2.4 MB/s eta 0:00:01
   ---------------------------------------- 32.8/32.8 MB 2.4 MB/s  0:00:13
Using cached numpy_financial-1.0.0-py3-none-any.whl (14 kB)
Using cached openmdao-3.42.0-py3-none-any.whl (13.6 MB)
Downloading networkx-3.6.1-py3-none-any.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------- ----------------------------- 0.5/2.1 MB 3.4 MB/s eta 0:00:01
   ------------------------- -------------- 1.3/2.1 MB 4.2 MB/s eta 0:00:01
   ---------------------------------------- 2.1/2.1 MB 3.9 MB/s  0:00:00
Downloading ortools-9.15.6755-cp311-cp311-win_amd64.whl (23.9 MB)
   ---------------------------------------- 0.0/23.9 MB ? eta -:--:--
    --------------------------------------- 0.5/23.9 MB 4.2 MB/s eta 0:00:06
   -- ------------------------------------- 1.3/23.9 MB 3.7 MB/s eta 0:00:07

In [4]:

examples_sites = pd.read_csv(f'{examples_filepath}examples_sites.csv', index_col=0, sep=';')
examples_sites

,case,name,longitude,latitude,altitude,input_ts_fn,sim_pars_fn,price_fn,price_col,H2_demand_col,input_HA_ts_fn,price_up_ts,price_dwn_ts
0,India,Indian_site_good_wind,77.500226,8.334294,679.803454,India/GWA2/input_ts_Indian_site_good_wind.csv,India/hpp_pars.yml,India/Indian_elec_price_t.csv,Price,India/H2_demand.csv,NaN,NaN,NaN
1,India,Indian_site_good_solar,68.542204,23.542099,29.883557,India/GWA2/input_ts_Indian_site_good_solar.csv,India/hpp_pars.yml,India/Indian_elec_price_t.csv,Price,India/H2_demand.csv,NaN,NaN,NaN
2,India,Indian_site_bad_solar_bad_wind,77.916878,17.292316,627.424643,India/GWA2/input_ts_Indian_site_bad_solar_bad_...,India/hpp_pars.yml,India/Indian_elec_price_t.csv,Price,India/H2_demand.csv,NaN,NaN,NaN
3,Europe,France_good_solar,4.229736,44.422011,204.000000,Europe/GWA2/input_ts_France_good_solar.csv,Europe/hpp_pars.yml,Europe/2030-EL_PRICE.csv,FR_R,Europe/H2_demand.csv,NaN,NaN,NaN
4,Europe,France_good_wind,-0.864258,48.744116,302.000000,Europe/GWA2/input_ts_France_good_wind.csv,Europe/hpp_pars.yml,Europe/2030-EL_PRICE.csv,FR_R,Europe/H2_demand.csv,NaN,NaN,NaN
5,Europe,France_bad_solar_n_wind,2.167969,47.428087,140.000000,Europe/GWA2/input_ts_France_bad_solar_n_wind.csv,Europe/hpp_pars.yml,Europe/2030-EL_PRICE.csv,FR_R,Europe/H2_demand.csv,NaN,NaN,NaN
6,Europe,Germany_bad_solar_n_wind,10.766602,49.310798,442.000000,Europe/GWA2/input_ts_Germany_bad_solar_n_wind.csv,Europe/hpp_pars.yml,Europe/2030-EL_PRICE.csv,DE_ME,Europe/H2_demand.csv,NaN,NaN,NaN
7,Europe,Germany_good_wind,7.873535,53.287111,5.000000,Europe/GWA2/input_ts_Germany_good_wind.csv,Europe/hpp_pars.yml,Europe/2030-EL_PRICE.csv,DE_NW,Europe/H2_demand.csv,NaN,NaN,NaN
8,Europe,Denmark_good_solar,11.813965,55.397760,42.000000,Europe/GWA2/input_ts_Denmark_good_solar.csv,Europe/hpp_pars.yml,Europe/2030-EL_PRICE.csv,DK_E,Europe/H2_demand.csv,NaN,NaN,NaN
9,Europe,Denmark_good_wind,8.594398,56.227322,85.000000,Europe/GWA2/input_ts_Denmark_good_wind.csv,Europe/hpp_pars.yml,Europe/2030-EL_PRICE.csv,DK_W,Europe/H2_demand.csv,NaN,NaN,NaN
10,Europe,Denmark_offshore,7.906111,55.529722,85.000000,Europe/GWA2/input_ts_Denmark_offshore.csv,Europe/hpp_pars_offshore.yml,Europe/2030-EL_PRICE.csv,DK_W,Europe/H2_demand.csv,NaN,NaN,NaN
11,Europe,Denmark_good_wind_BM,8.594398,56.227322,85.000000,Europe/GWA2_BM/input_ts_Denmark_good_wind_DA.csv,Europe/hpp_pars.yml,Europe/2030-EL_PRICE.csv,DK_W,Europe/H2_demand.csv,Europe/GWA2_BM/input_ts_Denmark_good_wind_HA.csv,Europe/BM_Prices/Up_reg_price.csv,Europe/BM_Prices/Down_reg_price.csv
12,Europe,Denmark_hybridization_wind_Norhede_Hjortmose,8.366400,56.095400,16.662000,Europe/GWA2/input_ts_Denmark_hybridization_win...,Europe/hpp_pars_Hjortmose.yml,Europe/2030-EL_PRICE.csv,DK_W,Europe/H2_demand.csv,NaN,NaN,NaN
13,Europe,Denmark_hybridization_solar_Langelinie,11.290641,54.717469,0.042000,Europe/GWA2/input_ts_Denmark_hybridization_sol...,Europe/hpp_pars_Langelinie.yml,Europe/2030-EL_PRICE.csv,DK_E,Europe/H2_demand.csv,NaN,NaN,NaN
14,Europe,Aalborg,9.924774,57.057163,19.000000,Europe/GWA2/input_ts_Aalborg_DKW.csv,Europe/hpp_pars.yml,Europe/2030-EL_PRICE.csv,DKW,Europe/H2_demand.csv,NaN,NaN,NaN
15,Europe,Aalesund,6.188221,62.475690,5.000000,Europe/GWA2/input_ts_Aalesund_NO5.csv,Europe/hpp_pars.yml,Europe/2030-EL_PRICE.csv,NO5,Europe/H2_demand.csv,NaN,NaN,NaN
16,Europe,Bodo,14.402733,67.279271,21.000000,Europe/GWA2/input_ts_Bodo_NO4.csv,Europe/hpp_pars.yml,Europe/2030-EL_PRICE.csv,NO4,Europe/H2_demand.csv,NaN,NaN,NaN
17,Europe,Brighton,-0.098877,50.823289,44.000000,Europe/GWA2/input_ts_Brighton_UK.csv,Europe/hpp_pars.yml,Europe/2030-EL_PRICE.csv,UK,Europe/H2_demand.csv,NaN,NaN,NaN
18,Europe,Bruges,3.217964,51.272441,4.000000,Europe/GWA2/input_ts_Bruges_BE.csv,Europe/hpp_pars.yml,Europe/2030-EL_PRICE.csv,BE,Europe/H2_demand.csv,NaN,NaN,NaN
19,Europe,Haapsalu,23.545074,58.933713,6.000000,Europe/GWA2/input_ts_Haapsalu_EE.csv,Europe/hpp_pars.yml,Europe/2030-EL_PRICE.csv,EE,Europe/H2_demand.csv,NaN,NaN,NaN
20,Europe,Kalmar,16.352463,56.663774,8.000000,Europe/GWA2/input_ts_Kalmar_SE4.csv,Europe/hpp_pars.yml,Europe/2030-EL_PRICE.csv,SE4,Europe/H2_demand.csv,NaN,NaN,NaN
21,Europe,Karlsruhe,8.404541,49.004547,115.000000,Europe/GWA2/input_ts_Karlsruhe_DE4W.csv,Europe/hpp_pars.yml,Europe/2030-EL_PRICE.csv,DE4W,Europe/H2_demand.csv,NaN,NaN,NaN
22,Europe,Kiruna,20.253296,67.858985,46.000000,Europe/GWA2/input_ts_Kiruna_SE1.csv,Europe/hpp_pars.yml,Europe/2030-EL_PRICE.csv,SE1,Europe/H2_demand.csv,NaN,NaN,NaN
23,Europe,Kristiansund,7.746391,63.116811,4.000000,Europe/GWA2/input_ts_Kristiansund_NO3.csv,Europe/hpp_pars.yml,Europe/2030-EL_PRICE.csv,NO3,Europe/H2_demand.csv,NaN,NaN,NaN
24,Europe,Liepaja,21.015816,56.509881,4.000000,Europe/GWA2/input_ts_Liepaja_LV.csv,Europe/hpp_pars.yml,Europe/2030-EL_PRICE.csv,LV,Europe/H2_demand.csv,NaN,NaN,NaN
25,Europe,Linkoping,15.595093,58.424730,49.000000,Europe/GWA2/input_ts_Linkoping_SE3.csv,Europe/hpp_pars.yml,Europe/2030-EL_PRICE.csv,SE3,Europe/H2_demand.csv,NaN,NaN,NaN
26,Europe,Lublin,22.585144,51.246444,173.000000,Europe/GWA2/input_ts_Lublin_PL.csv,Europe/hpp_pars.yml,Europe/2030-EL_PRICE.csv,PL,Europe/H2_demand.csv,NaN,NaN,NaN
27,Europe,Marijampole,23.348694,54.556137,73.000000,Europe/GWA2/input_ts_Marijampole_LT.csv,Europe/hpp_pars.yml,Europe/2030-EL_PRICE.csv,LT,Europe/H2_demand.csv,NaN,NaN,NaN
28,Europe,Munster,7.575760,51.968385,71.000000,Europe/GWA2/input_ts_Munster_DENW.csv,Europe/hpp_pars.yml,Europe/2030-EL_PRICE.csv,DENW,Europe/H2_demand.csv,NaN,NaN,NaN
29,Europe,Nuremberg,11.076965,49.452057,302.000000,Europe/GWA2/input_ts_Nuremberg_DE4S.csv,Europe/hpp_pars.yml,Europe/2030-EL_PRICE.csv,DE4S,Europe/H2_demand.csv,NaN,NaN,NaN
30,Europe,Ostersund,14.662628,63.174194,359.000000,Europe/GWA2/input_ts_Ostersund_SE2.csv,Europe/hpp_pars.yml,Europe/2030-EL_PRICE.csv,SE2,Europe/H2_demand.csv,NaN,NaN,NaN
31,Europe,Perpignan,2.862282,42.701614,46.000000,Europe/GWA2/input_ts_Perpignan_FRR.csv,Europe/hpp_pars.yml,Europe/2030-EL_PRICE.csv,FRR,Europe/H2_demand.csv,NaN,NaN,NaN
32,Europe,Rostock,12.156372,54.102892,13.000000,Europe/GWA2/input_ts_Rostock_DEME.csv,Europe/hpp_pars.yml,Europe/2030-EL_PRICE.csv,DEME,Europe/H2_demand.csv,NaN,NaN,NaN
33,Europe,Stavanger,5.732117,58.971251,35.000000,Europe/GWA2/input_ts_Stavanger_NO2.csv,Europe/hpp_pars.yml,Europe/2030-EL_PRICE.csv,NO2,Europe/H2_demand.csv,NaN,NaN,NaN
34,Europe,Tonsberg,10.415726,59.270442,29.000000,Europe/GWA2/input_ts_Tonsberg_NO1.csv,Europe/hpp_pars.yml,Europe/2030-EL_PRICE.csv,NO1,Europe/H2_demand.csv,NaN,NaN,NaN
35,Europe,Turku,22.266541,60.440963,34.000000,Europe/GWA2/input_ts_Turku_FIN.csv,Europe/hpp_pars.yml,Europe/2030-EL_PRICE.csv,FIN,Europe/H2_demand.csv,NaN,NaN,NaN
36,Europe,Vordingborg,11.907806,55.008339,6.000000,Europe/GWA2/input_ts_Vordingborg_DKE.csv,Europe/hpp_pars.yml,Europe/2030-EL_PRICE.csv,DKE,Europe/H2_demand.csv,NaN,NaN,NaN
37,Europe,Workum,5.446472,52.978829,1.000000,Europe/GWA2/input_ts_Workum_NLR.csv,Europe/hpp_pars.yml,Europe/2030-EL_PRICE.csv,NLR,Europe/H2_demand.csv,NaN,NaN,NaN

In [5]:
name = 'France_good_wind'
ex_site = examples_sites.loc[examples_sites.name == name]

longitude = ex_site['longitude'].values[0]
latitude = ex_site['latitude'].values[0]
altitude = ex_site['altitude'].values[0]

In [6]:
input_ts_fn = examples_filepath+ex_site['input_ts_fn'].values[0]

input_ts = pd.read_csv(input_ts_fn, index_col=0, parse_dates=True)

required_cols = [col for col in input_ts.columns if 'WD' not in col]
input_ts = input_ts.loc[:,required_cols]
input_ts

,WS_1,WS_50,WS_100,WS_150,WS_200,temp_air_1,ghi,dni,dhi,Price
2012-01-01 00:00:00,3.816262,9.189450,11.084209,12.271178,13.193283,284.873662,0.10670,0.0,0.10670,32.685
2012-01-01 01:00:00,3.433942,8.425198,10.193588,11.295483,12.177159,284.759079,0.05335,0.0,0.05335,32.685
2012-01-01 02:00:00,3.401840,8.457382,10.257751,11.500057,12.475967,284.682409,0.00000,0.0,0.00000,32.685
2012-01-01 03:00:00,3.552851,8.750878,10.595812,11.846432,12.862474,284.804835,0.00000,0.0,0.00000,32.685
2012-01-01 04:00:00,3.563602,8.849321,10.730704,12.023872,13.075707,284.912742,0.00000,0.0,0.00000,32.685
...,...,...,...,...,...,...,...,...,...,...
2012-12-30 19:00:00,3.431328,8.738007,10.644316,11.514788,12.815824,281.205509,0.00000,0.0,0.00000,37.591
2012-12-30 20:00:00,3.522005,8.956219,10.906332,11.806788,13.153907,281.139846,0.00000,0.0,0.00000,35.839
2012-12-30 21:00:00,3.546788,9.081438,11.071820,12.064809,13.412334,280.716650,0.00000,0.0,0.00000,35.362
2012-12-30 22:00:00,3.613134,9.352224,11.424145,12.542857,13.966094,280.646177,0.00000,0.0,0.00000,34.468
2012-12-30 23:00:00,3.672954,9.526146,11.639926,12.831741,14.247031,280.627905,0.00000,0.0,0.00000,33.417

In [7]:
sim_pars_fn = examples_filepath+ex_site['sim_pars_fn'].values[0]

with open(sim_pars_fn) as file:
    sim_pars = yaml.load(file, Loader=yaml.FullLoader)

print(sim_pars_fn)
sim_pars

c:/Users/dhmht/miniconda3/envs/hydesign/Lib/site-packages/hydesign/examples/Europe/hpp_pars.yml

{'G_MW': 300,
 'year': '2012',
 'N_life': 25,
 'wind_turbine_cost': 640000,
 'wind_civil_works_cost': 260000,
 'wind_fixed_onm_cost': 12600,
 'wind_variable_onm_cost': 1.35,
 'd_ref': 145,
 'hh_ref': 100,
 'p_rated_ref': 5.0,
 'wpp_efficiency': 1,
 'wind_deg_yr': [0, 25],
 'wind_deg': [0, 0.25],
 'share_WT_deg_types': 0.5,
 'solar_PV_cost': 110000,
 'solar_hardware_installation_cost': 100000,
 'solar_inverter_cost': 20000,
 'solar_fixed_onm_cost': 4500,
 'land_use_per_solar_MW': 0.01226,
 'tracking': 'No',
 'pv_deg_yr': [0, 1, 25],
 'pv_deg': [0.03, 0.03, 0.28],
 'latitude': None,
 'longitude': None,
 'altitude': None,
 'battery_energy_cost': 62000,
 'battery_power_cost': 16000,
 'battery_BOP_installation_commissioning_cost': 80000,
 'battery_control_system_cost': 2250,
 'battery_energy_onm_cost': 0,
 'battery_depth_of_discharge': 0.9,
 'battery_charge_efficiency': 0.985,
 'battery_price_reduction_per_year': 0.1,
 'min_LoH': 0.7,
 'n_full_power_hours_expected_per_day_at_peak_price': 0,
 'peak_hr_quantile': 0.9,
 'price_H2': 5,
 'storage_eff': 0.9,
 'ptg_deg_yr': [0, 25],
 'ptg_deg': [0.0, 0.25],
 'hhv': 39.3,
 'water_consumption': 9.4,
 'electrolyzer_capex_cost': 800000,
 'electrolyzer_opex_cost': 16000,
 'electrolyzer_power_electronics_cost': 0,
 'water_cost': 4,
 'water_treatment_cost': 2,
 'H2_storage_capex_cost': 300,
 'H2_storage_opex_cost': 3,
 'H2_transportation_cost': 5,
 'H2_transportation_distance': 0,
 'penalty_factor_H2': 0,
 'electrolyzer_eff_curve_name': 'PEM electrolyzer H2 production',
 'electrolyzer_eff_curve_type': 'production',
 'min_power_standby': 0.0,
 'hpp_BOS_soft_cost': 119940,
 'hpp_grid_connection_cost': 50000,
 'land_cost': 300000,
 'wind_WACC': 0.06,
 'solar_WACC': 0.06,
 'battery_WACC': 0.06,
 'tax_rate': 0.22,
 'ptg_WACC': 0.08,
 'phasing_yr': [-1, 0],
 'phasing_CAPEX': [1, 1],
 'inflation_yr': [-3, 0, 1, 25],
 'inflation': [0.1, 0.1, 0.06, 0.06],
 'ref_yr_inflation': 0,
 'depreciation_yr': [0, 25],
 'depreciation': [0, 1],
 'bi_directional_status': 0,
 'penalty_BM': 2000,
 'era5_zarr': '/groups/reanalyses/era5/app/era5.zarr',
 'ratio_gwa_era5': '/groups/INP/era5/ratio_gwa2_era5.nc',
 'era5_ghi_zarr': '/groups/INP/era5/ghi.zarr',
 'elevation_fn': '/groups/INP/era5/SRTMv3_plus_ViewFinder_coarsen.nc'}

In [8]:
rotor_diameter_m = 220
hub_height_m = 130
wt_rated_power_MW = 10
surface_tilt_deg = 35
surface_azimuth_deg = 180
DC_AC_ratio = 1.5

In [12]:
hpp = hpp_model(
        latitude=latitude,
        longitude=longitude,
        altitude=altitude,
        rotor_diameter_m = rotor_diameter_m,
        hub_height_m = hub_height_m,
        wt_rated_power_MW = wt_rated_power_MW,
        surface_tilt_deg = surface_tilt_deg,
        surface_azimuth_deg = surface_azimuth_deg,
        DC_AC_ratio = DC_AC_ratio,
        num_batteries = 5,
        work_dir = './',
        sim_pars_fn = sim_pars_fn,
        input_ts_fn = input_ts_fn,
)

Fixed parameters on the site
-------------------------------
longitude = -0.864258
latitude = 48.744116
altitude = 302.0